apiVersion: v1
kind: Service
metadata:
  name: foyer-devops-service
spec:
  type: NodePort
  selector:
    app: foyer-devops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
